print("twee personen nemen del aan een loopwedstrijd van rondjes over 400m")
print("Hoeveel rondjes gaan de 2 deelneemers lopen:")
num = int(input('rondjes '))
print("Persoon 1:")
name = input('Naam:')
print("rondje1:") 
rondje1 = int(input('rondje1:'))
print("rondje2:")
rondje2 = int(input('rondje2:'))
